import { Theme } from "../theme.slint";
export component AppMenu inherits Rectangle {
    height: 32px;
    background: Theme.layer-fill;
    HorizontalLayout {
        padding-left: 12px;
        spacing: 16px;
        Text { text: "File"; color: Theme.text-primary; }
        Text { text: "Edit"; color: Theme.text-primary; }
        Text { text: "View"; color: Theme.text-primary; }
        Text { text: "Session"; color: Theme.text-primary; }
        Text { text: "Help"; color: Theme.text-primary; }
    }
}
